# https://taskfile.dev

version: "3"

tasks:
  deps-web:
    dir: ./webapp
    sources:
      - ./package.json
      - ./package-lock.json
    cmds:
      - npm install

  run-backend:
    aliases:
      - run
      - backend
      - b
    cmds:
      - cargo run

  run-web:
    aliases:
      - web
      - w
    deps:
      - deps-web
    dir: ./webapp
    cmds:
      - npm start
