skipprecache = false

[storage]
location = "../data"

[server]
port = 5000
address = "localhost"
allowedorigin = "http://localhost:3000"

[cache]
type = "memory"
cachelocation = ".cache"
# redisaddress = "redis://localhost/1"